import re

weapon_map = {
    "A Thousand Blazing Suns": "AThousandBlazingSuns",
    "A Thousand Floating Dreams": "AThousandFloatingDreams",
        "A Thousand Floating Dream": "AThousandFloatingDreams",
    "Absolution": "Absolution",
    "Akuoumaru": "Akuoumaru",
    "Alley Hunter": "AlleyHunter",
    "Amenoma Kageuchi": "AmenomaKageuchi",
    "Amos' Bow": "AmosBow",
    "Apprentice's Notes": "ApprenticesNotes",
    "Aqua Simulacra": "AquaSimulacra",
    "Aquilla Favonia": "AquilaFavonia",
    "Aquila Favonia": "AquilaFavonia",
    "Ash-Graven Drinking Horn": "AshGravenDrinkingHorn",
    "Astral Vulture's Crimson Plumage": "AstralVulturesCrimsonPlumage",
    "Athame Artis": "AthameArtis",
    "Ballad of the Boundless Blue": "BalladOfTheBoundlessBlue",
    "Ballad of the Fjords": "BalladOfTheFjords",
    "Beacon of the Reed Sea": "BeaconOfTheReedSea",
    "Beginner's Protector": "BeginnersProtector",
    "Black Tassel": "BlackTassel",
    "Blackcliff Agate": "BlackcliffAgate",
    "Blackcliff Longsword": "BlackcliffLongsword",
    "Blackcliff Pole": "BlackcliffPole",
    "Blackcliff Slasher": "BlackcliffSlasher",
    "Blackcliff Warbow": "BlackcliffWarbow",
    "Blackmarrow Lantern": "BlackmarrowLantern",
    "Bloodsoaked Ruins": "BloodsoakedRuins",
    "Bloodtainted Greatsword": "BloodtaintedGreatsword",
    "Calamity of Eshu": "CalamityOfEshu",
    "Calamity Queller": "CalamityQueller",
    "Cashflow Supervision": "CashflowSupervision",
    "Chain Breaker": "ChainBreaker",
    "Cinnabar Spindle": "CinnabarSpindle",
    "Cloudforged": "Cloudforged",
    "Compound Bow": "CompoundBow",
    "Cool Steel": "CoolSteel",
    "Crane's Echoing Call": "CranesEchoingCall",
    "Crescent Pike": "CrescentPike",
    "Crimson Moon's Semblance": "CrimsonMoonsSemblance",
    "Dark Iron Sword": "DarkIronSword",
    "Dawning Frost": "DawningFrost",
    "Deathmatch": "Deathmatch",
    "Debate Club": "DebateClub",
    "Dialogues of the Desert Sages": "DialoguesOfTheDesertSages",
    "Dodoco Tales": "DodocoTales",
    "Dragon's Bane": "DragonsBane",
    "Dragonspine Spear": "DragonspineSpear",
    "Dull Blade": "DullBlade",
    "Earth Shaker": "EarthShaker",
    "Elegy for the End": "ElegyForTheEnd",
    "Emerald Orb": "EmeraldOrb",
    "End of the Line": "EndOfTheLine",
    "Engulfing Lightning": "EngulfingLightning",
    "Etherlight Spindlelute": "EtherlightSpindlelute",
    "Everlasting Moonglow": "EverlastingMoonglow",
    "Eye of Perception": "EyeOfPerception",
    "Fading Twilight": "FadingTwilight",
    "Fang of the Mountain King": "FangOfTheMountainKing",
    "Favonius Codex": "FavoniusCodex",
    "Favonius Greatsword": "FavoniusGreatsword",
    "Favonius Lance": "FavoniusLance",
    "Favonius Sword": "FavoniusSword",
    "Favonius Warbow": "FavoniusWarbow",
    "Ferrous Shadow": "FerrousShadow",
    "Festering Desire": "FesteringDesire",
    "Fillet Blade": "FilletBlade",
    "Finale of the Deep": "FinaleOfTheDeep",
    "Flame-Forged Insight": "FlameForgedInsight",
    "Fleuve Cendre Ferryman": "FleuveCendreFerryman",
    "Flower-Wreathed Feathers": "FlowerWreathedFeathers",
    "Flowing Purity": "FlowingPurity",
    "Flute of Ezpitzal": "FluteOfEzpitzal",
    "Footprint of the Rainbow": "FootprintOfTheRainbow",
    "Forest Regalia": "ForestRegalia",
    "Fractured Halo": "FracturedHalo",
    "Freedom-Sworn": "FreedomSworn",
    "Frostbearer": "Frostbearer",
    "Fruit of Fulfillment": "FruitOfFulfillment",
        "Fruit of Fulfilment": "FruitOfFulfillment",
    "Fruitful Hook": "FruitfulHook",
    "Hakushin Ring": "HakushinRing",
    "Halberd": "Halberd",
    "Hamayumi": "Hamayumi",
    "Haran Geppaku Futsu": "HaranGeppakuFutsu",
    "Harbinger of Dawn": "HarbingerOfDawn",
    "Hunter's Bow": "HuntersBow",
    "Hunter's Path": "HuntersPath",
    "Ibis Piercer": "IbisPiercer",
    "Iron Point": "IronPoint",
    "Iron Sting": "IronSting",
    "Jadefall's Splendor": "JadefallsSplendor",
    "Kagotsurube Isshin": "KagotsurubeIsshin",
    "Kagura's Verity": "KagurasVerity",
    "Katsuragikiri Nagamasa": "KatsuragikiriNagamasa",
    "Key of Khaj-Nisut": "KeyOfKhajNisut",
        "Key of Khaj Nisut": "KeyOfKhajNisut",
    "King's Squire": "KingsSquire",
    "Kitain Cross Spear": "KitainCrossSpear",
    "Light of Foliar Incision": "LightOfFoliarIncision",
    "Lion's Roar": "LionsRoar",
    "Lithic Blade": "LithicBlade",
    "Lithic Spear": "LithicSpear",
    "Lost Prayer to the Sacred Winds": "LostPrayerToTheSacredWinds",
        "Lost Prayer to Sacred Winds": "LostPrayerToTheSacredWinds",
    "Lumidouce Elegy": "LumidouceElegy",
    "Luxurious Sea-Lord": "LuxuriousSeaLord",
    "Magic Guide": "MagicGuide",
    "Mailed Flower": "MailedFlower",
    "Makhaira Aquamarine": "MakhairaAquamarine",
    "Mappa Mare": "MappaMare",
    "Master Key": "MasterKey",
    "Memory of Dust": "MemoryOfDust",
    "Messenger": "Messenger",
    "Missive Windspear": "MissiveWindspear",
    "Mistsplitter Reforged": "MistsplitterReforged",
    "Mitternachts Waltz": "MitternachtsWaltz",
    "Moonpiercer": "Moonpiercer",
    "Moonweaver's Dawn": "MoonweaversDawn",
    "Mountain-Bracing Bolt": "MountainBracingBolt",
    "Mouun's Moon": "MouunsMoon",
    "Nightweaver's Looking Glass": "NightweaversLookingGlass",
    "Nocturne's Curtain Call": "NocturnesCurtainCall",
    "Oathsworn Eye": "OathswornEye",
    "Old Merc's Pal": "OldMercsPal",
    "Otherworldly Story": "OtherworldlyStory",
    "Peak Patrol Song": "PeakPatrolSong",
    "Pocket Grimoire": "PocketGrimoire",
    "Polar Star": "PolarStar",
    "Portable Power Saw": "PortablePowerSaw",
    "Predator": "Predator",
    "Primordial Jade Cutter": "PrimordialJadeCutter",
    "Primordial Jade Winged-Spear": "PrimordialJadeWingedSpear",
    "Prospector's Drill": "ProspectorsDrill",
    "Prospector's Shovel": "ProspectorsShovel",
    "Prototype Amber": "PrototypeAmber",
    "Prototype Archaic": "PrototypeArchaic",
    "Prototype Crescent": "PrototypeCrescent",
    "Prototype Rancour": "PrototypeRancour",
    "Prototype Starglitter": "PrototypeStarglitter",
    "Quantum Cat-alyst": "QuantumCatalyst",
    "Rainbow Serpent's Rain Bow": "RainbowSerpentsRainBow",
    "Rainslasher": "Rainslasher",
    "Range Gauge": "RangeGauge",
    "Raven Bow": "RavenBow",
    "Recurve Bow": "RecurveBow",
    "Redhorn Stonethresher": "RedhornStonethresher",
    "Reliquary of Truth": "ReliquaryOfTruth",
    "Rightful Reward": "RightfulReward",
    "Ring of Yaxche": "RingOfYaxche",
    "Royal Bow": "RoyalBow",
    "Royal Greatsword": "RoyalGreatsword",
    "Royal Grimoire": "RoyalGrimoire",
    "Royal Longsword": "RoyalLongsword",
    "Royal Spear": "RoyalSpear",
    "Rust": "Rust",
    "Sacrificer's Staff": "SacrificersStaff",
    "Sacrificial Bow": "SacrificialBow",
    "Sacrificial Fragments": "SacrificialFragments",
    "Sacrificial Greatsword": "SacrificialGreatsword",
    "Sacrificial Jade": "SacrificialJade",
        "Sacrifical Jade": "SacrificialJade",
    "Sacrificial Sword": "SacrificialSword",
    "Sapwood Blade": "SapwoodBlade",
    "Scion of the Blazing Sun": "ScionOfTheBlazingSun",
    "Seasoned Hunter's Bow": "SeasonedHuntersBow",
    "Sequence of Solitude": "SequenceOfSolitude",
    "Serenity's Call": "SerenitysCall",
    "Serpent Spine": "SerpentSpine",
    "Sharpshooter's Oath": "SharpshootersOath",
    "Silver Sword": "SilverSword",
    "Silvershower Heartstrings": "SilvershowerHeartstrings",
    "Skyrider Greatsword": "SkyriderGreatsword",
    "Skyrider Sword": "SkyriderSword",
    "Skyward Atlas": "SkywardAtlas",
    "Skyward Blade": "SkywardBlade",
    "Skyward Harp": "SkywardHarp",
    "Skyward Pride": "SkywardPride",
    "Skyward Spine": "SkywardSpine",
    "Slingshot": "Slingshot",
    "Snare Hook": "SnareHook",
    "Snow-Tombed Starsilver": "SnowTombedStarsilver",
    "Solar Pearl": "SolarPearl",
    "Song of Broken Pines": "SongOfBrokenPines",
    "Song of Stillness": "SongOfStillness",
    "Splendor of Tranquil Waters": "SplendorOfTranquilWaters",
    "Staff of Homa": "StaffOfHoma",
    "Staff of the Scarlet Sands": "StaffOfTheScarletSands",
    "Starcaller's Watch": "StarcallersWatch",
    "Sturdy Bone": "SturdyBone",
    "Summit Shaper": "SummitShaper",
    "Sunny Morning Sleep-In": "SunnyMorningSleepIn",
    "Surf's Up!": "SurfsUp",
        "Surf's Up": "SurfsUp",
        "SurfsUp!": "SurfsUp",
    "Sword of Descension": "SwordOfDescension",
    "Sword of Narzissenkreuz": "SwordOfNarzissenkreuz",
    "Symphonist of Scents": "SymphonistOfScents",
    "Talking Stick": "TalkingStick",
    "Tamayuratei no Ohanashi": "TamayurateiNoOhanashi",
    "The Alley Flash": "TheAlleyFlash",
    "Alley Flash": "TheAlleyFlash",
    "The Bell": "TheBell",
    "The Black Sword": "TheBlackSword",
    "\"The Catch\"": "TheCatch",
    "The Daybreak Chronicles": "TheDaybreakChronicles",
    "The Dockhand's Assistant": "TheDockhandsAssistant",
    "The First Great Magic": "TheFirstGreatMagic",
    "The Flute": "TheFlute",
    "The Stringless": "TheStringless",
    "The Unforged": "TheUnforged",
    "The Viridescent Hunt": "TheViridescentHunt",
        "Viridescent Hunt": "TheViridescentHunt",
    "The Widsith": "TheWidsith",
    "Thrilling Tales of Dragon Slayers": "ThrillingTalesOfDragonSlayers",
    "Thundering Pulse": "ThunderingPulse",
    "Tidal Shadow": "TidalShadow",
    "Tome of the Eternal Flow": "TomeOfTheEternalFlow",
    "Toukabou Shigure": "ToukabouShigure",
    "Traveler's Handy Sword": "TravelersHandySword",
    "Tullaytulah's Remembrance": "TulaytullahsRemembrance",
    "Tulaytullah's Rememberance": "TulaytullahsRemembrance",
    "Tulaytullah's Remembrance": "TulaytullahsRemembrance",
    "Twin Nephrite": "TwinNephrite",
    "\"Ultimate Overlord's Mega Magic Sword\"": "UltimateOverlordsMegaMagicSword",
        "Ultimate Overlord's Mega Magic Sword": "UltimateOverlordsMegaMagicSword",
    "Uraku Misugiri": "UrakuMisugiri",
    "Verdict": "Verdict",
    "Vivid Notions": "VividNotions",
        "Vivid Notion": "VividNotions",
    "Vortex Vanquisher": "VortexVanquisher",
    "Wandering Evenstar": "WanderingEvenstar",
    "Waster Greatsword": "WasterGreatsword",
    "Wavebreaker's Fin": "WavebreakersFin",
    "Waveriding Whirl": "WaveridingWhirl",
    "White Iron Greatsword": "WhiteIronGreatsword",
    "White Tassel": "WhiteTassel",
    "Whiteblind": "Whiteblind",
    "Windblume Ode": "WindblumeOde",
    "Wine and Song": "WineAndSong",
    "Wolf-Fang": "WolfFang",
    "Wolf Fang": "WolfFang",
    "Wolf's Gravestone": "WolfsGravestone",
    "Xiphos' Moonlight": "XiphosMoonlight"
}


def replace_weapons(text):
    # Sort by length descending to prevent partial replacements of longer phrases
    sorted_keys = sorted(weapon_map.keys(), key=lambda k: -len(k))

    for key in sorted_keys:
        escaped_key = re.escape(key)

        # Check if key starts/ends with a word character (alphanumeric + underscore)
        # We use lookahead/lookbehind or simple string checks.
        # Using regex checks is safest to align with \w definition.

        start_boundary = r'\b' if re.match(r'^\w', key) else ''
        end_boundary = r'\b' if re.search(r'\w$', key) else ''

        # Construct pattern only using boundaries where appropriate
        pattern = r'{}{}{}'.format(start_boundary, escaped_key, end_boundary)

        text = re.sub(pattern, weapon_map[key], text)
    return text


# Read input file
input_file = 'input.txt'
output_file = 'output.txt'

try:
    with open(input_file, 'r') as file:
        content = file.read()
    updated_content = replace_weapons(content)
    with open(output_file, 'w') as file:
        file.write(updated_content)
    print(f"Successfully replaced weapons in {input_file}. Output written to {output_file}.")
except FileNotFoundError:
    print(f"Error: The file {input_file} was not found.")
except Exception as e:
    print(f"An error occurred: {e}")