import numpy as np
import sys

def create_preferences_from_dict(character_preferences, item_labels):
    """
    Create a preferences array from a dictionary of character preferences.

    Parameters:
    - character_preferences: A dictionary where keys are character names, and values are
      dictionaries mapping item names to preference values.
    - item_labels: List of item names.

    Returns:
    - A 2D preferences array.
    """
    num_characters = len(character_preferences)
    num_items = len(item_labels)
    preferences = np.full((num_characters, num_items), 999)  # Default penalty

    for char_idx, (char, item_prefs) in enumerate(character_preferences.items()):
        for item, value in item_prefs.items():
            item_indices = [i for i, label in enumerate(item_labels) if label == item]
            for item_idx in item_indices:
                preferences[char_idx, item_idx] = value

    return preferences


# Example input
character_preferences = {
    # SWORD
    # "Traveler": {"MistsplitterReforged": 3.25, "PrimordialJadeCutter": 3.38, "FreedomSworn": 3.5, "FavoniusSword": 4.12, "UrakuMisugiri": 4.44, "HaranGeppakuFutsu": 4.5, "LightOfFoliarIncision": 4.5, "Absolution": 4.62, "SacrificialSword": 4.75, "SplendorOfTranquilWaters": 4.75, "SummitShaper": 4.88, "FesteringDesire": 5.25, "SkywardBlade": 5.25, "FinaleOfTheDeep": 5.75, "FleuveCendreFerryman": 5.75, "IronSting": 5.75, "WolfFang": 5.78, "PeakPatrolSong": 5.88, "AmenomaKageuchi": 5.88, "HarbingerOfDawn": 6.0, "AquilaFavonia": 6.12, "KeyOfKhajNisut": 6.25, "LionsRoar": 6.25, "DarkIronSword": 6.38, "SapwoodBlade": 6.38, "SkyriderSword": 6.38},
    # "Bennett": {"MistsplitterReforged": 1.0, "Absolution": 2.0, "FreedomSworn": 4.0, "Azurelight": 4.5, "AquilaFavonia": 4.5, "TheAlleyFlash": 4.5, "PrimordialJadeCutter": 4.5, "HaranGeppakuFutsu": 4.5, "UrakuMisugiri": 5.0, "PeakPatrolSong": 5.5, "SkywardBlade": 5.5, "LightOfFoliarIncision": 5.5, "SapwoodBlade": 6.0, "SplendorOfTranquilWaters": 6.0, "SummitShaper": 6.0, "PrototypeRancour": 6.5, "CalamityOfEshu": 6.5, "WolfFang": 6.5, "FavoniusSword": 7.0, "FinaleOfTheDeep": 7.0, "TheBlackSword": 7.0},
    # "Durin": {"AthameArtis": 1.0, "PrimordialJadeCutter": 2.0, "Azurelight": 2.0, "MistsplitterReforged": 2.5, "HaranGeppakuFutsu": 4.0, "Absolution": 5.0, "LightOfFoliarIncision": 6.0, "FreedomSworn": 6.0, "FinaleOfTheDeep": 6.0, "WolfFang": 6.0, "SummitShaper": 7.0, "UrakuMisugiri": 7.0, "SplendorOfTranquilWaters": 7.0, "MoonweaversDawn": 7.0, "LionsRoar": 7.0},
    # "Kuki Shinobu": {"FreedomSworn": 1.33, "KeyOfKhajNisut": 2.33, "XiphosMoonlight": 3.67, "IronSting": 4.0, "PrimordialJadeCutter": 4.0, "FesteringDesire": 4.33, "FavoniusSword": 4.33, "SapwoodBlade": 5.0, "ToukabouShigure": 5.67, "DarkIronSword": 5.67, "TheDockhandsAssistant": 5.67},
    # "Keqing": {"MistsplitterReforged": 1.0, "PrimordialJadeCutter": 1.0, "HaranGeppakuFutsu": 1.5, "LightOfFoliarIncision": 1.5, "UrakuMisugiri": 2.0, "HarbingerOfDawn": 3.0, "SplendorOfTranquilWaters": 3.0, "FreedomSworn": 3.0, "Absolution": 3.5, "ToukabouShigure": 4.0, "WolfFang": 4.5, "IronSting": 5.0, "TheBlackSword": 5.5, "CalamityOfEshu": 6.0, "FinaleOfTheDeep": 6.5, "SummitShaper": 6.5, "LionsRoar": 6.5},
    # # "Clorinde": {"Absolution": 1.0, "LightOfFoliarIncision": 2.0, "HaranGeppakuFutsu": 2.0, "MistsplitterReforged": 3.0, "PrimordialJadeCutter": 3.0, "UrakuMisugiri": 3.0, "FreedomSworn": 3.0, "CalamityOfEshu": 4.0, "FinaleOfTheDeep": 5.0, "TheBlackSword": 5.0},
    # "Kirara": {"KeyOfKhajNisut": 1.0, "SapwoodBlade": 2.0, "TheDockhandsAssistant": 3.0, "FavoniusSword": 4.0, "FreedomSworn": 5.0, "SacrificialSword": 6.0},
    # "Alhaitham": {"LightOfFoliarIncision": 1.0, "UrakuMisugiri": 2.0, "PrimordialJadeCutter": 2.0, "MistsplitterReforged": 3.0, "HaranGeppakuFutsu": 3.0, "FreedomSworn": 4.0, "WolfFang": 5.0, "ToukabouShigure": 6.0, "TheBlackSword": 7.0, "SummitShaper": 8.0, "IronSting": 8.0, "BlackcliffLongsword": 8.0, "HarbingerOfDawn": 8.0, "XiphosMoonlight": 9.0, "FesteringDesire": 9.0, "SkywardBlade": 10.0},
    # "Xingqiu": {"SkywardBlade": 3.0, "AthameArtis": 3.0, "PrimordialJadeCutter": 3.0, "MistsplitterReforged": 3.5, "FavoniusSword": 4.0, "Azurelight": 4.0, "HaranGeppakuFutsu": 4.0, "LightOfFoliarIncision": 4.0, "Absolution": 4.0, "SummitShaper": 4.5, "UrakuMisugiri": 4.5, "SplendorOfTranquilWaters": 5.0, "AmenomaKageuchi": 5.5, "FleuveCendreFerryman": 5.5, "WolfFang": 5.5, "SacrificialSword": 6.5, "FinaleOfTheDeep": 6.5},
    # "Dahlia": {"FavoniusSword": 1.0, "KeyOfKhajNisut": 2.0, "TheDockhandsAssistant": 3.0, "PeakPatrolSong": 4.0, "FreedomSworn": 4.0, "SkyriderSword": 5.0},
    # "Kamisato Ayato": {"HaranGeppakuFutsu": 1.0, "PrimordialJadeCutter": 1.0, "MistsplitterReforged": 2.0, "LightOfFoliarIncision": 3.0, "TheBlackSword": 4.0, "SkywardBlade": 5.0, "SplendorOfTranquilWaters": 5.0, "SummitShaper": 6.0, "FinaleOfTheDeep": 7.0, "KagotsurubeIsshin": 7.0, "LionsRoar": 8.0, "HarbingerOfDawn": 9.0, "TheFlute": 9.0, "SwordOfNarzissenkreuz": 9.0},
    # "Nilou": {"KeyOfKhajNisut": 1.0, "TheDockhandsAssistant": 2.0, "SerenitysCall": 3.0},
    # "Furina": {"SplendorOfTranquilWaters": 1.0, "PrimordialJadeCutter": 2.0, "FesteringDesire": 3.0, "KeyOfKhajNisut": 3.0, "UrakuMisugiri": 3.0, "FleuveCendreFerryman": 4.0, "FavoniusSword": 4.0, "WolfFang": 5.0, "HaranGeppakuFutsu": 5.0, "LightOfFoliarIncision": 5.0, "MistsplitterReforged": 5.0, "SkywardBlade": 6.0, "TheDockhandsAssistant": 6.0, "HarbingerOfDawn": 6.0},
    # "Kaeya": {"MistsplitterReforged": 1.5, "PrimordialJadeCutter": 2.5, "Absolution": 3.0, "LightOfFoliarIncision": 3.0, "HaranGeppakuFutsu": 3.0, "SplendorOfTranquilWaters": 4.0, "SummitShaper": 4.5, "HarbingerOfDawn": 5.0, "FinaleOfTheDeep": 5.5, "UrakuMisugiri": 5.5, "FreedomSworn": 6.0, "ToukabouShigure": 6.0, "IronSting": 6.0, "SkywardBlade": 6.5, "LionsRoar": 6.5, "AmenomaKageuchi": 7.0, "FavoniusSword": 7.0},
    # "Layla": {"PrimordialJadeCutter": 2.0, "HarbingerOfDawn": 2.0, "KeyOfKhajNisut": 3.0, "TheDockhandsAssistant": 4.5, "FavoniusSword": 5.0, "UrakuMisugiri": 5.0, "SplendorOfTranquilWaters": 5.0, "LightOfFoliarIncision": 5.0, "MistsplitterReforged": 5.5, "WolfFang": 5.5, "FreedomSworn": 6.0, "SkyriderSword": 6.5},
    # "Qiqi": {"SacrificialSword": 1.0, "FavoniusSword": 2.0, "PeakPatrolSong": 3.0, "SkywardBlade": 4.0, "SapwoodBlade": 5.0, "FleuveCendreFerryman": 6.0, "AmenomaKageuchi": 7.0},
    # # "Kamisato Ayaka": {"MistsplitterReforged": 1.0, "HaranGeppakuFutsu": 2.0, "LightOfFoliarIncision": 3.0, "PrimordialJadeCutter": 3.0, "SummitShaper": 3.0, "FinaleOfTheDeep": 4.5, "AquilaFavonia": 5.0, "SkywardBlade": 5.0, "AmenomaKageuchi": 6.0, "TheBlackSword": 6.0, "KagotsurubeIsshin": 6.0, "HarbingerOfDawn": 7.0},
    # "Skirk": {"Azurelight": 1.0, "HaranGeppakuFutsu": 2.0, "MistsplitterReforged": 3.0, "PrimordialJadeCutter": 3.0, "CalamityOfEshu": 4.0, "UrakuMisugiri": 5.0, "Absolution": 5.0, "LightOfFoliarIncision": 5.0, "FinaleOfTheDeep": 6.0, "SummitShaper": 6.0, "TheBlackSword": 7.0},
    # "Lynette": {"FavoniusSword": 1.0, "FleuveCendreFerryman": 2.0, "SacrificialSword": 2.0, "AmenomaKageuchi": 2.0, "SkywardBlade": 2.0, "FreedomSworn": 3.0},
    # "Jean": {"FreedomSworn": 1.5, "PrimordialJadeCutter": 3.5, "FavoniusSword": 4.0, "MistsplitterReforged": 4.5, "HaranGeppakuFutsu": 4.5, "SkywardBlade": 5.0, "FesteringDesire": 5.0, "AmenomaKageuchi": 5.0, "XiphosMoonlight": 5.0, "SummitShaper": 5.5, "IronSting": 5.5, "ToukabouShigure": 5.5, "AquilaFavonia": 6.0, "TheFlute": 6.5, "SapwoodBlade": 6.5, "LionsRoar": 6.5, "DarkIronSword": 6.5},
    # "Kaedehara Kazuha": {"FreedomSworn": 1.0, "FavoniusSword": 2.0, "XiphosMoonlight": 3.0, "SacrificialSword": 4.0, "FleuveCendreFerryman": 4.0, "SkywardBlade": 4.0, "IronSting": 5.0, "ToukabouShigure": 5.0, "SkyriderSword": 5.0},
    # "Albedo": {"PeakPatrolSong": 1.0, "UrakuMisugiri": 1.0, "HarbingerOfDawn": 2.0, "FluteOfEzpitzal": 2.0, "PrimordialJadeCutter": 2.0, "CinnabarSpindle": 2.0},
    # # "Chiori": {"UrakuMisugiri": 1.0, "PrimordialJadeCutter": 2.0, "PeakPatrolSong": 2.0, "HarbingerOfDawn": 3.0, "CinnabarSpindle": 3.0, "LightOfFoliarIncision": 3.0, "HaranGeppakuFutsu": 3.0, "MistsplitterReforged": 3.0, "SplendorOfTranquilWaters": 3.0, "WolfFang": 4.0},
    # "Xilonen": {"PeakPatrolSong": 1.0, "FreedomSworn": 2.0, "FavoniusSword": 3.0, "FluteOfEzpitzal": 4.0, "SkyriderSword": 5.0},

    # CLAYMORE
    # "Xinyan": {"RedhornStonethresher": 2.0, "SerpentSpine": 3.0, "SkywardPride": 3.33, "TheUnforged": 4.0, "SongOfBrokenPines": 4.33, "WolfsGravestone": 4.67, "BeaconOfTheReedSea": 5.67, "LuxuriousSeaLord": 6.0, "BlackcliffSlasher": 6.33, "LithicBlade": 6.67, "SacrificialGreatsword": 6.67, "SnowTombedStarsilver": 7.0, "PrototypeArchaic": 7.0, "Whiteblind": 7.0, "FavoniusGreatsword": 7.33},
    # # "Gaming": {"SerpentSpine": 1.0, "RedhornStonethresher": 1.0, "AThousandBlazingSuns": 1.0, "Verdict": 1.0, "BeaconOfTheReedSea": 2.0, "FruitfulHook": 3.0, "WolfsGravestone": 3.0, "Rainslasher": 3.0, "MailedFlower": 4.0, "LithicBlade": 4.0, "TheUnforged": 4.0, "TidalShadow": 5.0, "UltimateOverlordsMegaMagicSword": 5.0, "MakhairaAquamarine": 5.0},
    # "Diluc": {"BeaconOfTheReedSea": 1.0, "RedhornStonethresher": 1.0, "AThousandBlazingSuns": 1.0, "Verdict": 2.0, "SerpentSpine": 2.0, "FangOfTheMountainKing": 3.0, "WolfsGravestone": 4.0, "TheUnforged": 4.0, "SongOfBrokenPines": 5.0, "Rainslasher": 5.0, "MailedFlower": 5.0, "TidalShadow": 6.0, "BlackcliffSlasher": 6.0, "SkywardPride": 6.0, "EarthShaker": 7.0},
    # "Dehya": {"MailedFlower": 3.0, "WolfsGravestone": 3.33, "Rainslasher": 3.33, "FavoniusGreatsword": 3.33, "MakhairaAquamarine": 3.33, "BeaconOfTheReedSea": 3.67, "RedhornStonethresher": 4.0, "Verdict": 4.0, "FangOfTheMountainKing": 4.33, "SerpentSpine": 4.33, "BloodtaintedGreatsword": 4.33, "TidalShadow": 4.67, "UltimateOverlordsMegaMagicSword": 4.67, "TalkingStick": 4.67, "TheUnforged": 4.67, "AThousandBlazingSuns": 4.67, "SkywardPride": 4.67, "TheBell": 4.67, "SacrificialGreatsword": 4.67, "Akuoumaru": 5.0},
    # "Mavuika": {"AThousandBlazingSuns": 1.0, "RedhornStonethresher": 2.0, "Verdict": 2.0, "BeaconOfTheReedSea": 3.0, "MailedFlower": 4.0, "WolfsGravestone": 4.0, "TheUnforged": 4.0, "SerpentSpine": 5.0, "FangOfTheMountainKing": 5.0, "TidalShadow": 6.0, "Rainslasher": 7.0},
    # "Aino": {"FavoniusGreatsword": 1.0, "MakhairaAquamarine": 2.0, "FlameForgedInsight": 3.0, "MasterKey": 3.0},
    # "Beidou": {"WolfsGravestone": 2.0, "AThousandBlazingSuns": 2.0, "BeaconOfTheReedSea": 2.5, "RedhornStonethresher": 2.5, "Verdict": 3.0, "SerpentSpine": 3.5, "TheUnforged": 3.5, "FangOfTheMountainKing": 3.5, "TidalShadow": 4.5, "Akuoumaru": 6.0, "UltimateOverlordsMegaMagicSword": 6.0, "LuxuriousSeaLord": 6.5, "SkywardPride": 6.5, "LithicBlade": 7.0},
    # "Razor": {"WolfsGravestone": 3.0, "BeaconOfTheReedSea": 3.0, "SongOfBrokenPines": 3.5, "RedhornStonethresher": 4.0, "TheUnforged": 4.5, "MailedFlower": 5.0, "MakhairaAquamarine": 5.0, "SerpentSpine": 5.0, "Rainslasher": 5.5, "BloodtaintedGreatsword": 5.5, "SkywardPride": 5.5, "FavoniusGreatsword": 6.0, "LithicBlade": 6.0, "ForestRegalia": 6.5, "PrototypeArchaic": 6.5},
    # "Dori": {"FavoniusGreatsword": 1.0, "SacrificialGreatsword": 2.0, "KatsuragikiriNagamasa": 3.0, "ForestRegalia": 4.0},
    # "Kaveh": {"FlameForgedInsight": 1.0, "FavoniusGreatsword": 1.0, "SacrificialGreatsword": 2.0, "MailedFlower": 3.0, "WolfsGravestone": 4.0, "SongOfBrokenPines": 4.0, "MakhairaAquamarine": 5.0, "KatsuragikiriNagamasa": 5.0, "SkywardPride": 6.0, "ForestRegalia": 6.0, "Rainslasher": 6.0},
    # "Kinich": {"FangOfTheMountainKing": 1.0, "AThousandBlazingSuns": 2.0, "BeaconOfTheReedSea": 2.0, "SerpentSpine": 3.0, "Verdict": 4.0, "EarthShaker": 5.0, "WolfsGravestone": 5.0, "RedhornStonethresher": 5.0},
    # "Chongyun": {"SacrificialGreatsword": 1.0, "SerpentSpine": 2.5, "AThousandBlazingSuns": 3.0, "RedhornStonethresher": 3.5, "BeaconOfTheReedSea": 3.5, "Verdict": 3.5, "MailedFlower": 4.0, "FangOfTheMountainKing": 4.0, "SkywardPride": 4.5, "TheUnforged": 4.5, "LuxuriousSeaLord": 4.5, "Akuoumaru": 4.5, "MakhairaAquamarine": 4.5, "TidalShadow": 5.0, "BlackcliffSlasher": 5.0, "FavoniusGreatsword": 5.0, "WolfsGravestone": 5.0},
    # "Freminet": {"FangOfTheMountainKing": 1.0, "AThousandBlazingSuns": 1.0, "SkywardPride": 2.0, "Verdict": 2.0, "WolfsGravestone": 2.5, "SongOfBrokenPines": 3.5, "BeaconOfTheReedSea": 3.5, "RedhornStonethresher": 4.0, "TheUnforged": 4.0, "SerpentSpine": 4.5, "TidalShadow": 5.5, "PrototypeArchaic": 6.0, "SnowTombedStarsilver": 6.5, "MailedFlower": 6.5},
    # "Eula": {"SongOfBrokenPines": 1.0, "WolfsGravestone": 2.0, "BeaconOfTheReedSea": 2.0, "SkywardPride": 3.0, "Verdict": 3.0, "TheUnforged": 4.0, "RedhornStonethresher": 5.0, "SerpentSpine": 6.0, "UltimateOverlordsMegaMagicSword": 6.0, "LuxuriousSeaLord": 7.0, "Akuoumaru": 7.0, "TidalShadow": 7.0, "LithicBlade": 8.0, "PrototypeArchaic": 9.0, "SnowTombedStarsilver": 10.0, "SkyriderGreatsword": 11.0},
    # "Sayu": {"FavoniusGreatsword": 1.0, "WolfsGravestone": 2.0, "KatsuragikiriNagamasa": 3.0, "SkywardPride": 4.0, "SacrificialGreatsword": 5.0, "MakhairaAquamarine": 6.0, "MailedFlower": 7.0, "ForestRegalia": 8.0, "Rainslasher": 9.0, "BloodtaintedGreatsword": 10.0},
    # "Noelle": {"RedhornStonethresher": 1.5, "SerpentSpine": 2.5, "FavoniusGreatsword": 3.0, "SkywardPride": 3.5, "Whiteblind": 4.5},
    # "Arataki Itto": {"RedhornStonethresher": 1.0, "SerpentSpine": 2.0, "BeaconOfTheReedSea": 2.0, "Verdict": 2.0, "AThousandBlazingSuns": 2.0, "Whiteblind": 3.0, "SkywardPride": 3.0},
    # # "Navia": {"Verdict": 1.0, "AThousandBlazingSuns": 1.0, "SerpentSpine": 2.0, "BeaconOfTheReedSea": 3.0, "SkywardPride": 4.0, "RedhornStonethresher": 5.0, "FangOfTheMountainKing": 6.0, "WolfsGravestone": 7.0, "TheUnforged": 7.0, "TalkingStick": 8.0, "TidalShadow": 9.0, "UltimateOverlordsMegaMagicSword": 10.0, "EarthShaker": 11.0, "PrototypeArchaic": 12.0},


    # BOW
    # "Amber": {"TheFirstGreatMagic": 3.0, "AquaSimulacra": 3.5, "ThunderingPulse": 4.0, "SkywardHarp": 4.0, "PolarStar": 4.0, "Slingshot": 4.5, "AmosBow": 5.0, "HuntersPath": 5.0, "TheViridescentHunt": 5.0, "IbisPiercer": 5.5, "Hamayumi": 6.0, "PrototypeCrescent": 6.0, "ElegyForTheEnd": 6.0, "SongOfStillness": 6.5, "FavoniusWarbow": 6.5, "WindblumeOde": 7.0, "TheStringless": 7.0, "SacrificialBow": 7.0, "SharpshootersOath": 7.5, "KingsSquire": 7.5, "ScionOfTheBlazingSun": 7.5},
    # "Yoimiya": {"ThunderingPulse": 1.0, "AquaSimulacra": 2.0, "TheFirstGreatMagic": 2.0, "PolarStar": 3.0, "HuntersPath": 4.0, "SkywardHarp": 4.0, "Slingshot": 5.0, "AmosBow": 5.0, "Rust": 6.0},
    # "Lyney": {"TheFirstGreatMagic": 1.0, "AstralVulturesCrimsonPlumage": 1.0, "AquaSimulacra": 2.0, "ThunderingPulse": 3.0, "SkywardHarp": 4.0, "AmosBow": 5.0, "PolarStar": 6.0, "SongOfStillness": 6.0, "PrototypeCrescent": 6.0},
    # "Fischl": {"PolarStar": 1.0, "AquaSimulacra": 2.0, "HuntersPath": 2.0, "ThunderingPulse": 3.0, "TheFirstGreatMagic": 3.0, "SkywardHarp": 3.5, "AstralVulturesCrimsonPlumage": 4.5, "SongOfStillness": 5.5, "ChainBreaker": 5.5, "TheStringless": 6.0, "AmosBow": 6.5, "AlleyHunter": 6.5, "TheViridescentHunt": 6.5, "FadingTwilight": 7.0, "WindblumeOde": 7.0},
    # "Kujou Sara": {"SkywardHarp": 1.0, "PolarStar": 2.0, "ElegyForTheEnd": 2.0, "TheFirstGreatMagic": 3.0, "AquaSimulacra": 4.0, "HuntersPath": 4.0, "ThunderingPulse": 5.0, "AmosBow": 6.0, "FadingTwilight": 7.0, "MouunsMoon": 7.0, "AlleyHunter": 7.0, "TheViridescentHunt": 7.0, "ScionOfTheBlazingSun": 7.0, "SacrificialBow": 8.0, "ChainBreaker": 8.0, "FavoniusWarbow": 9.0},
    # "Sethos": {"HuntersPath": 1.0, "AstralVulturesCrimsonPlumage": 1.0, "Slingshot": 1.0},
    # "Ororon": {"PolarStar": 1.0, "TheFirstGreatMagic": 1.0, "ThunderingPulse": 2.0, "AquaSimulacra": 2.0, "HuntersPath": 2.0, "SkywardHarp": 2.0, "AstralVulturesCrimsonPlumage": 3.0, "ChainBreaker": 4.0, "AlleyHunter": 4.0, "RangeGauge": 5.0, "SongOfStillness": 5.0, "ElegyForTheEnd": 6.0, "FadingTwilight": 6.0, "FavoniusWarbow": 7.0},
    # "Collei": {"ElegyForTheEnd": 1.0, "FavoniusWarbow": 2.0, "PolarStar": 3.0, "SacrificialBow": 4.0},
    # "Tighnari": {"HuntersPath": 1.0, "AstralVulturesCrimsonPlumage": 2.0, "AquaSimulacra": 2.0, "PolarStar": 2.0, "TheFirstGreatMagic": 2.0, "SkywardHarp": 3.0, "ThunderingPulse": 3.0, "ElegyForTheEnd": 4.0, "AmosBow": 4.0, "FadingTwilight": 4.0, "ScionOfTheBlazingSun": 5.0, "TheViridescentHunt": 5.0, "Slingshot": 6.0, "RangeGauge": 6.0, "WindblumeOde": 6.0, "SongOfStillness": 6.0, "PrototypeCrescent": 7.0},
    # "Tartaglia": {"PolarStar": 1.0, "HuntersPath": 2.0, "AquaSimulacra": 2.0, "SkywardHarp": 2.0, "ThunderingPulse": 2.0, "AstralVulturesCrimsonPlumage": 2.0, "TheFirstGreatMagic": 3.0, "TheViridescentHunt": 4.0, "KingsSquire": 5.0, "AmosBow": 5.0, "TheStringless": 5.0, "ScionOfTheBlazingSun": 6.0, "BlackcliffWarbow": 6.0, "ChainBreaker": 6.0, "WindblumeOde": 7.0, "Hamayumi": 7.0, "MouunsMoon": 7.0, "Rust": 7.0},
    # "Yelan": {"AquaSimulacra": 2.0, "SilvershowerHeartstrings": 3.5, "ElegyForTheEnd": 4.0, "MouunsMoon": 4.0, "TheStringless": 4.0, "Slingshot": 4.0, "SequenceOfSolitude": 4.0, "FavoniusWarbow": 4.5, "HuntersPath": 4.5, "PolarStar": 4.5, "ThunderingPulse": 4.5, "SkywardHarp": 4.5, "FadingTwilight": 5.0, "SacrificialBow": 5.5, "RecurveBow": 5.5},
    # # "Sigewinne": {"SilvershowerHeartstrings": 1.0, "SequenceOfSolitude": 2.0, "RecurveBow": 2.0, "FavoniusWarbow": 2.0, "ElegyForTheEnd": 2.0, "SacrificialBow": 2.0},
    # "Diona": {"FavoniusWarbow": 1.0, "SacrificialBow": 1.0, "ElegyForTheEnd": 2.0, "SilvershowerHeartstrings": 3.0, "RecurveBow": 4.0, "SequenceOfSolitude": 4.0},
    # "Ganyu": {"TheFirstGreatMagic": 1.67, "AstralVulturesCrimsonPlumage": 2.33, "AquaSimulacra": 2.33, "PolarStar": 2.33, "AmosBow": 3.33, "ThunderingPulse": 3.33, "SkywardHarp": 4.0, "HuntersPath": 4.67, "SongOfStillness": 5.33, "FlowerWreathedFeathers": 5.67, "PrototypeCrescent": 6.0, "Hamayumi": 6.33, "ScionOfTheBlazingSun": 6.33, "MouunsMoon": 6.33},
    # "Aloy": {"ThunderingPulse": 1.0, "PolarStar": 2.0, "SkywardHarp": 3.0, "TheStringless": 4.0, "AmosBow": 5.0, "AlleyHunter": 6.0, "PrototypeCrescent": 7.0, "Predator": 8.0, "SacrificialBow": 9.0, "Slingshot": 10.0},
    # "Faruzan": {"FavoniusWarbow": 1.0, "ElegyForTheEnd": 2.0, "SnareHook": 3.0, "EndOfTheLine": 4.0, "FadingTwilight": 5.0, "SacrificialBow": 5.0},
    # "Jahoda": {"FavoniusWarbow": 1.0, "ElegyForTheEnd": 2.0, "RainbowSerpentsRainBow": 3.0, "SnareHook": 4.0},
    # "Venti": {"TheDaybreakChronicles": 1.0, "PolarStar": 2.0, "HuntersPath": 3.0, "AquaSimulacra": 3.0, "SkywardHarp": 3.0, "AstralVulturesCrimsonPlumage": 3.5, "TheFirstGreatMagic": 3.5, "ThunderingPulse": 4.0, "MouunsMoon": 6.0, "SongOfStillness": 6.0, "AmosBow": 6.0, "TheStringless": 6.5, "AlleyHunter": 6.5, "Slingshot": 6.5, "TheViridescentHunt": 6.5, "Rust": 6.5},
    # # Chasca has sig weapon
    # # "Chasca": {"AstralVulturesCrimsonPlumage": 1.0, "AquaSimulacra": 2.0, "TheFirstGreatMagic": 2.0, "ThunderingPulse": 3.0, "SkywardHarp": 4.0, "AmosBow": 5.0, "PolarStar": 5.0, "ScionOfTheBlazingSun": 5.0, "ChainBreaker": 6.0, "SongOfStillness": 6.0, "FlowerWreathedFeathers": 6.0, "Hamayumi": 6.0, "RangeGauge": 7.0},
    # "Gorou": {"FavoniusWarbow": 1.0, "SnareHook": 2.0, "SacrificialBow": 3.0, "ElegyForTheEnd": 4.0}

    # POLEARM
    "Xiangling": {"EngulfingLightning": 1.5, "StaffOfTheScarletSands": 2.0, "LumidouceElegy": 2.5, "StaffOfHoma": 2.5, "TheCatch": 2.5, "PrimordialJadeWingedSpear": 4.5, "SymphonistOfScents": 4.5, "Deathmatch": 4.5, "BalladOfTheFjords": 4.5, "VortexVanquisher": 5.0, "CalamityQueller": 5.0, "CrimsonMoonsSemblance": 5.0, "WavebreakersFin": 5.0, "DragonsBane": 5.0, "MissiveWindspear": 5.5, "KitainCrossSpear": 5.5, "FavoniusLance": 6.0, "SkywardSpine": 6.0, "LithicSpear": 6.5, "PrototypeStarglitter": 7.0},
    "Thoma": {"FavoniusLance": 1.5, "KitainCrossSpear": 2.5, "EngulfingLightning": 4.5, "TheCatch": 5.0, "DragonsBane": 6.0, "BlackTassel": 6.0, "PrototypeStarglitter": 6.0, "Moonpiercer": 6.5, "SkywardSpine": 6.5, "RightfulReward": 7.0},
    "Chevreuse": {"SymphonistOfScents": 1.0, "EngulfingLightning": 4.0, "StaffOfHoma": 4.5, "StaffOfTheScarletSands": 5.0, "LumidouceElegy": 5.0, "CalamityQueller": 5.5, "SkywardSpine": 5.5, "FavoniusLance": 6.0, "PrimordialJadeWingedSpear": 6.0, "VortexVanquisher": 6.0, "TheCatch": 6.5, "DialoguesOfTheDesertSages": 7.0, "Deathmatch": 7.0, "BalladOfTheFjords": 7.0, "BlackTassel": 7.5, "RightfulReward": 7.5, "MissiveWindspear": 7.5, "PrototypeStarglitter": 8.0},
    "Hu Tao": {"StaffOfHoma": 1.0, "StaffOfTheScarletSands": 2.0, "BalladOfTheFjords": 3.0, "LumidouceElegy": 3.0, "DragonsBane": 4.0, "Deathmatch": 4.0, "PrimordialJadeWingedSpear": 5.0, "LithicSpear": 6.0, "MissiveWindspear": 7.0, "WhiteTassel": 8.0, "BlackcliffPole": 8.0, "KitainCrossSpear": 8.0, "RightfulReward": 8.0},
    "Arlecchino": {"CrimsonMoonsSemblance": 1.0, "PrimordialJadeWingedSpear": 2.0, "StaffOfTheScarletSands": 2.0, "StaffOfHoma": 3.0, "LumidouceElegy": 3.0, "CalamityQueller": 3.0, "VortexVanquisher": 4.0, "Deathmatch": 5.0, "WhiteTassel": 6.0, "BalladOfTheFjords": 7.0},
    "Iansan": {"EngulfingLightning": 1.0, "SymphonistOfScents": 1.0, "CalamityQueller": 2.0, "FavoniusLance": 2.0, "TamayurateiNoOhanashi": 2.0, "SkywardSpine": 3.0, "VortexVanquisher": 4.0, "MissiveWindspear": 5.0, "KitainCrossSpear": 6.0},
    "Raiden Shogun": {"EngulfingLightning": 2.5, "StaffOfHoma": 3.0, "StaffOfTheScarletSands": 3.0, "SymphonistOfScents": 3.0, "LumidouceElegy": 3.0, "PrimordialJadeWingedSpear": 3.0, "CalamityQueller": 3.5, "Deathmatch": 3.5, "VortexVanquisher": 4.0, "DragonsBane": 4.5, "TheCatch": 4.5, "SkywardSpine": 4.5, "Moonpiercer": 5.0, "WavebreakersFin": 5.0, "LithicSpear": 5.0, "KitainCrossSpear": 5.5, "FavoniusLance": 5.5},
    # "Cyno": {"StaffOfTheScarletSands": 1.0, "BalladOfTheFjords": 2.5, "PrimordialJadeWingedSpear": 2.5, "Deathmatch": 3.5, "LumidouceElegy": 4.0, "StaffOfHoma": 4.0, "WhiteTassel": 4.0, "KitainCrossSpear": 5.0, "MissiveWindspear": 5.5, "SkywardSpine": 5.5, "DragonsBane": 6.0, "FavoniusLance": 6.5},
    "Ineffa": {"FracturedHalo": 1.0, "StaffOfTheScarletSands": 2.0, "SymphonistOfScents": 3.0, "LumidouceElegy": 4.0, "StaffOfHoma": 4.0, "BloodsoakedRuins": 5.0, "CalamityQueller": 6.0, "PrimordialJadeWingedSpear": 7.0, "CrimsonMoonsSemblance": 7.0, "Deathmatch": 7.0, "EngulfingLightning": 8.0, "BalladOfTheFjords": 8.0, "VortexVanquisher": 9.0, "ProspectorsShovel": 9.0, "SacrificersStaff": 9.0, "SkywardSpine": 9.0},
    # "Flins": {"BloodsoakedRuins": 1.0, "StaffOfTheScarletSands": 2.0, "FracturedHalo": 3.0, "StaffOfHoma": 3.0, "SymphonistOfScents": 4.0, "PrimordialJadeWingedSpear": 4.0, "LumidouceElegy": 4.0, "BalladOfTheFjords": 5.0, "Deathmatch": 5.0, "CrimsonMoonsSemblance": 5.0, "CalamityQueller": 5.0, "SkywardSpine": 5.0, "VortexVanquisher": 5.0, "TamayurateiNoOhanashi": 6.0, "EngulfingLightning": 6.0, "ProspectorsShovel": 6.0, "BlackcliffPole": 6.0},
    "Yaoyao": {"FavoniusLance": 1.0, "DialoguesOfTheDesertSages": 2.0, "BlackTassel": 3.0, "RightfulReward": 3.0, "Moonpiercer": 4.0, "KitainCrossSpear": 5.0},
    "Emilie": {"LumidouceElegy": 1.0, "CalamityQueller": 2.0, "SymphonistOfScents": 3.0, "StaffOfHoma": 3.0, "EngulfingLightning": 4.0, "StaffOfTheScarletSands": 4.0, "PrimordialJadeWingedSpear": 5.0, "CrimsonMoonsSemblance": 5.0, "Deathmatch": 6.0, "SkywardSpine": 7.0, "TamayurateiNoOhanashi": 7.0, "MissiveWindspear": 8.0, "LithicSpear": 8.0, "ProspectorsDrill": 8.0, "FavoniusLance": 9.0, "KitainCrossSpear": 10.0},
    "Candace": {"FavoniusLance": 1.0, "EngulfingLightning": 2.0, "StaffOfHoma": 3.0, "Deathmatch": 3.0, "TheCatch": 3.0, "PrototypeStarglitter": 4.0, "SkywardSpine": 5.0, "BlackTassel": 6.0},
    "Rosaria": {"LumidouceElegy": 3.0, "StaffOfTheScarletSands": 3.33, "PrimordialJadeWingedSpear": 4.0, "StaffOfHoma": 4.33, "CalamityQueller": 4.33, "CrimsonMoonsSemblance": 4.67, "EngulfingLightning": 4.67, "FavoniusLance": 4.67, "Deathmatch": 5.0, "VortexVanquisher": 5.33, "SkywardSpine": 5.33, "WavebreakersFin": 6.0, "TheCatch": 6.33, "MissiveWindspear": 6.67, "TamayurateiNoOhanashi": 6.67, "DragonsBane": 7.0},
    "Mika": {"SymphonistOfScents": 1.0, "FavoniusLance": 1.0, "DialoguesOfTheDesertSages": 2.0, "EngulfingLightning": 3.0, "PrototypeStarglitter": 4.0, "TheCatch": 4.0, "RightfulReward": 4.0, "BlackTassel": 5.0},
    # "Shenhe": {"CalamityQueller": 1.0, "EngulfingLightning": 2.0, "VortexVanquisher": 3.0, "SymphonistOfScents": 4.0, "SkywardSpine": 5.0, "FavoniusLance": 6.0, "TamayurateiNoOhanashi": 6.0, "LithicSpear": 7.0, "WavebreakersFin": 8.0, "MissiveWindspear": 9.0, "PrototypeStarglitter": 10.0, "ProspectorsShovel": 10.0},
    # "Escoffier": {"SymphonistOfScents": 1.0, "CalamityQueller": 2.5, "EngulfingLightning": 3.5, "StaffOfHoma": 3.5, "LumidouceElegy": 4.0, "StaffOfTheScarletSands": 5.0, "VortexVanquisher": 5.0, "SkywardSpine": 5.0, "PrimordialJadeWingedSpear": 5.5, "CrimsonMoonsSemblance": 5.5, "KitainCrossSpear": 6.0, "Deathmatch": 6.33, "FavoniusLance": 6.5, "ProspectorsDrill": 6.5, "TamayurateiNoOhanashi": 7.0, "MountainBracingBolt": 7.0, "WavebreakersFin": 7.0},
    # Xiao gets sig weapon
    # "Xiao": {"FracturedHalo": 1.0, "StaffOfHoma": 1.0, "PrimordialJadeWingedSpear": 1.0, "LumidouceElegy": 1.0, "SymphonistOfScents": 1.0, "StaffOfTheScarletSands": 2.0, "CalamityQueller": 3.0, "Deathmatch": 3.0, "CrimsonMoonsSemblance": 3.0, "VortexVanquisher": 3.0, "SkywardSpine": 3.0, "BlackcliffPole": 4.0, "TamayurateiNoOhanashi": 4.0, "LithicSpear": 5.0, "MissiveWindspear": 6.0, "ProspectorsDrill": 6.0, "WavebreakersFin": 6.0, "FavoniusLance": 7.0, "WhiteTassel": 8.0},
    "Yun Jin": {"FavoniusLance": 1.0, "EngulfingLightning": 2.0, "TheCatch": 3.0, "PrototypeStarglitter": 3.0, "KitainCrossSpear": 3.0},
    "Kachina": {"FavoniusLance": 1.0, "FootprintOfTheRainbow": 2.0, "EngulfingLightning": 3.0, "PrototypeStarglitter": 4.0},
    # Zhongli gets sig weapon
    # "Zhongli": {"StaffOfHoma": 1.5, "LumidouceElegy": 2.0, "PrimordialJadeWingedSpear": 2.5, "SkywardSpine": 3.0, "VortexVanquisher": 3.0, "CalamityQueller": 3.0, "TheCatch": 3.5, "Deathmatch": 4.0, "EngulfingLightning": 4.5, "LithicSpear": 5.0, "BlackcliffPole": 5.5, "FavoniusLance": 6.0, "MissiveWindspear": 6.0, "BlackTassel": 6.5}

    # CATALYST
    # "Yanfei": {"ReliquaryOfTruth": 2.5, "TomeOfTheEternalFlow": 2.5, "CashflowSupervision": 3.0, "VividNotions": 3.0, "SurfsUp": 3.0, "StarcallersWatch": 3.0, "PrototypeAmber": 3.0, "AThousandFloatingDreams": 3.5, "FavoniusCodex": 3.5, "FlowingPurity": 4.0, "TheWidsith": 4.0, "DawningFrost": 4.0, "ThrillingTalesOfDragonSlayers": 4.0},
    # "Klee": {"ReliquaryOfTruth": 1.0, "LostPrayerToTheSacredWinds": 2.0, "KagurasVerity": 2.0, "VividNotions": 2.0, "TomeOfTheEternalFlow": 3.0, "CashflowSupervision": 3.0, "TulaytullahsRemembrance": 4.0, "SurfsUp": 4.0, "SkywardAtlas": 5.0, "TheWidsith": 6.0, "SolarPearl": 6.0, "SacrificialJade": 7.0, "FlowingPurity": 8.0},
    # "Lisa": {"ReliquaryOfTruth": 3.33, "AThousandFloatingDreams": 3.67, "VividNotions": 4.0, "KagurasVerity": 4.67, "LostPrayerToTheSacredWinds": 5.0, "TomeOfTheEternalFlow": 5.67, "SurfsUp": 5.67, "TheWidsith": 6.67, "SolarPearl": 7.33, "SacrificialJade": 7.33, "EtherlightSpindlelute": 7.67, "FruitOfFulfillment": 7.67, "StarcallersWatch": 7.67, "FlowingPurity": 8.0, "MappaMare": 8.0, "FavoniusCodex": 8.0, "CashflowSupervision": 8.33, "HakushinRing": 8.33, "SacrificialFragments": 8.33, "WanderingEvenstar": 8.33, "OathswornEye": 8.67, "MagicGuide": 8.67, "ThrillingTalesOfDragonSlayers": 9.33},
    # # "Yae Miko": {"KagurasVerity": 1.0, "SkywardAtlas": 3.0, "LostPrayerToTheSacredWinds": 3.5, "AThousandFloatingDreams": 3.5, "SolarPearl": 5.0, "TheWidsith": 5.0, "SunnyMorningSleepIn": 5.5, "OathswornEye": 6.0, "TomeOfTheEternalFlow": 6.0, "MemoryOfDust": 6.5, "TulaytullahsRemembrance": 6.5, "HakushinRing": 7.0, "MappaMare": 8.0},
    # # Varesa uses sig
    # # "Varesa": {"VividNotions": 1.0, "ReliquaryOfTruth": 2.0, "KagurasVerity": 3.0, "LostPrayerToTheSacredWinds": 4.0, "CranesEchoingCall": 5.0, "TomeOfTheEternalFlow": 6.0, "SurfsUp": 6.0, "CashflowSupervision": 6.0, "TulaytullahsRemembrance": 7.0, "TheWidsith": 8.0, "SkywardAtlas": 8.0, "SacrificialJade": 9.0, "SolarPearl": 10.0, "BlackcliffAgate": 10.0, "DawningFrost": 10.0, "FlowingPurity": 10.0},
    # # Nahida uses sig
    # # "Nahida": {"AThousandFloatingDreams": 1.0, "SunnyMorningSleepIn": 1.0, "KagurasVerity": 2.0, "SacrificialFragments": 3.0, "EtherlightSpindlelute": 3.0, "WanderingEvenstar": 4.0, "TheWidsith": 5.0, "SacrificialJade": 5.0, "SkywardAtlas": 6.0, "LostPrayerToTheSacredWinds": 6.0, "MemoryOfDust": 6.0, "SolarPearl": 6.0, "FavoniusCodex": 7.0, "MappaMare": 8.0, "MagicGuide": 8.0, "HakushinRing": 8.0, "ThrillingTalesOfDragonSlayers": 9.0, "PrototypeAmber": 10.0},
    # # "Baizhu": {"JadefallsSplendor": 1.0, "PrototypeAmber": 2.0, "FavoniusCodex": 3.0, "HakushinRing": 4.0, "ThrillingTalesOfDragonSlayers": 5.0, "AThousandFloatingDreams": 6.0},
    # "Lauma": {"NightweaversLookingGlass": 1.0, "AThousandFloatingDreams": 2.0, "StarcallersWatch": 3.0, "SunnyMorningSleepIn": 3.0, "ReliquaryOfTruth": 3.0, "EtherlightSpindlelute": 3.5, "SacrificialFragments": 4.0, "BlackmarrowLantern": 4.5, "SurfsUp": 4.5, "WanderingEvenstar": 4.5, "FruitOfFulfillment": 5.0},
    # # "Nefer": {"ReliquaryOfTruth": 1.0, "NocturnesCurtainCall": 2.0, "NightweaversLookingGlass": 3.0, "SunnyMorningSleepIn": 4.0, "StarcallersWatch": 4.0, "BlackmarrowLantern": 5.0, "AThousandFloatingDreams": 5.0, "TomeOfTheEternalFlow": 5.0, "SurfsUp": 5.0, "DawningFrost": 5.0, "TheWidsith": 6.0},
    # "Barbara": {"ThrillingTalesOfDragonSlayers": 3.0, "EverlastingMoonglow": 3.5, "StarcallersWatch": 3.5, "PrototypeAmber": 4.0, "AshGravenDrinkingHorn": 4.0, "AThousandFloatingDreams": 4.0, "SunnyMorningSleepIn": 4.0, "FavoniusCodex": 4.5, "SacrificialFragments": 4.5, "EtherlightSpindlelute": 4.5, "HakushinRing": 5.0, "MagicGuide": 5.0},
    # "Mona": {"SkywardAtlas": 3.0, "TheWidsith": 3.0, "LostPrayerToTheSacredWinds": 4.33, "SolarPearl": 5.0, "ThrillingTalesOfDragonSlayers": 5.33, "FavoniusCodex": 5.67, "MemoryOfDust": 5.67, "AThousandFloatingDreams": 6.0, "DodocoTales": 6.0, "PrototypeAmber": 6.33, "BlackcliffAgate": 6.33, "MappaMare": 6.33, "WineAndSong": 6.67},
    # "Sangonomiya Kokomi": {"PrototypeAmber": 3.0, "AshGravenDrinkingHorn": 3.0, "ThrillingTalesOfDragonSlayers": 3.33, "HakushinRing": 3.67, "EverlastingMoonglow": 3.67, "StarcallersWatch": 3.67, "SacrificialFragments": 4.0, "FlowingPurity": 4.0, "RingOfYaxche": 4.0, "AThousandFloatingDreams": 4.0, "SunnyMorningSleepIn": 4.0, "EtherlightSpindlelute": 4.33, "MagicGuide": 4.67, "FruitOfFulfillment": 4.67},
    # # "Neuvillette": {"TomeOfTheEternalFlow": 1.0, "SacrificialJade": 2.0, "SurfsUp": 2.0, "ReliquaryOfTruth": 2.0, "JadefallsSplendor": 3.0, "PrototypeAmber": 3.0, "CashflowSupervision": 3.0, "TheWidsith": 3.0, "KagurasVerity": 3.0, "LostPrayerToTheSacredWinds": 3.0, "AshGravenDrinkingHorn": 4.0},
    # "Mualani": {"SurfsUp": 1.0, "ReliquaryOfTruth": 2.0, "AThousandFloatingDreams": 3.0, "TomeOfTheEternalFlow": 4.0, "StarcallersWatch": 4.0, "SacrificialJade": 5.0, "SunnyMorningSleepIn": 6.0, "RingOfYaxche": 7.0, "TheWidsith": 7.0},
    # # needs Prototype Amber for healing
    # # "Columbina": {"NocturnesCurtainCall": 1.0, "PrototypeAmber": 2.0, "SacrificialJade": 2.0, "FavoniusCodex": 3.0},
    # "Charlotte": {"PrototypeAmber": 1.0, "FavoniusCodex": 1.0, "ThrillingTalesOfDragonSlayers": 2.0, "OathswornEye": 3.0, "WineAndSong": 3.0},
    # "Wriothesley": {"CashflowSupervision": 1.0, "TulaytullahsRemembrance": 1.0, "LostPrayerToTheSacredWinds": 2.0, "TomeOfTheEternalFlow": 2.0, "SkywardAtlas": 2.5, "AThousandFloatingDreams": 3.5, "TheWidsith": 3.5, "BalladOfTheBoundlessBlue": 3.5, "MemoryOfDust": 4.0, "KagurasVerity": 4.0, "MappaMare": 4.5, "FlowingPurity": 4.5},
    # # "Citlali": {"StarcallersWatch": 1.0, "ThrillingTalesOfDragonSlayers": 2.0, "FavoniusCodex": 2.0, "EtherlightSpindlelute": 2.0, "SacrificialFragments": 2.0, "WanderingEvenstar": 2.0},
    # "Sucrose": {"AThousandFloatingDreams": 1.0, "SunnyMorningSleepIn": 1.0, "WanderingEvenstar": 2.0, "SacrificialFragments": 3.0, "ThrillingTalesOfDragonSlayers": 3.0, "HakushinRing": 4.0, "MagicGuide": 5.0, "FavoniusCodex": 6.0},
    # "Shikanoin Heizou": {"KagurasVerity": 3.5, "SkywardAtlas": 3.5, "SunnyMorningSleepIn": 3.5, "LostPrayerToTheSacredWinds": 4.0, "CashflowSupervision": 4.0, "TomeOfTheEternalFlow": 4.0, "MappaMare": 4.0, "AThousandFloatingDreams": 4.0, "TulaytullahsRemembrance": 4.5, "SolarPearl": 4.5, "MemoryOfDust": 4.5, "TheWidsith": 4.5, "SacrificialFragments": 4.5, "WanderingEvenstar": 4.5, "FlowingPurity": 5.0, "FavoniusCodex": 5.0, "ThrillingTalesOfDragonSlayers": 5.0, "HakushinRing": 5.0, "PrototypeAmber": 5.0},
    # "Lan Yan": {"StarcallersWatch": 1.0, "ThrillingTalesOfDragonSlayers": 2.5, "FavoniusCodex": 3.5, "CranesEchoingCall": 4.5, "SacrificialFragments": 4.5, "WanderingEvenstar": 4.5, "HakushinRing": 5.5, "PrototypeAmber": 6.5},
    # "Ifa": {"SunnyMorningSleepIn": 3.0, "AThousandFloatingDreams": 3.0, "StarcallersWatch": 3.5, "TulaytullahsRemembrance": 4.0, "WanderingEvenstar": 4.5, "MappaMare": 4.5, "VividNotions": 4.5, "SacrificialFragments": 5.0, "SkywardAtlas": 5.0, "SurfsUp": 5.0, "HakushinRing": 5.5, "TomeOfTheEternalFlow": 5.5, "KagurasVerity": 5.5, "LostPrayerToTheSacredWinds": 5.5, "CashflowSupervision": 5.5, "ThrillingTalesOfDragonSlayers": 6.0, "FlowingPurity": 6.0, "TheWidsith": 6.0, "MemoryOfDust": 6.0},
    # "Wanderer": {"TulaytullahsRemembrance": 1.0, "LostPrayerToTheSacredWinds": 2.0, "MemoryOfDust": 3.0, "SkywardAtlas": 3.0, "TheWidsith": 3.0, "DodocoTales": 4.0, "KagurasVerity": 4.0, "TomeOfTheEternalFlow": 4.0, "SolarPearl": 5.0, "BalladOfTheBoundlessBlue": 6.0, "BlackcliffAgate": 7.0, "EyeOfPerception": 7.5, "MappaMare": 8.5, "Frostbearer": 8.5},
    # # Xianyun uses sig
    # # "Xianyun": {"CranesEchoingCall": 1.0, "OathswornEye": 3.5, "SkywardAtlas": 3.5, "MemoryOfDust": 3.5, "FavoniusCodex": 4.0, "CashflowSupervision": 4.0, "ThrillingTalesOfDragonSlayers": 4.5, "WineAndSong": 5.0, "FlowingPurity": 5.5, "BalladOfTheBoundlessBlue": 6.0, "HakushinRing": 6.0, "PrototypeAmber": 7.0, "Frostbearer": 7.0},
    # "Yumemizuki Mizuki": {"SunnyMorningSleepIn": 1.0, "StarcallersWatch": 2.0, "AThousandFloatingDreams": 3.0, "SacrificialFragments": 4.0, "FavoniusCodex": 4.0, "FruitOfFulfillment": 4.0, "HakushinRing": 5.0, "WanderingEvenstar": 5.0, "MagicGuide": 5.0},
    # "Ningguang": {"KagurasVerity": 1.0, "LostPrayerToTheSacredWinds": 1.0, "SurfsUp": 2.0, "TomeOfTheEternalFlow": 3.0, "CashflowSupervision": 3.0, "SkywardAtlas": 4.0, "MemoryOfDust": 5.0, "TulaytullahsRemembrance": 5.0, "TheWidsith": 5.0, "SolarPearl": 6.0, "CranesEchoingCall": 6.0, "FlowingPurity": 7.0, "DodocoTales": 8.0}
}
item_labels = [
    # "VividNotions",
    # "CranesEchoingCall",
    # "AThousandFloatingDreams",
    "AThousandFloatingDreams",
    "MemoryOfDust",
    "LostPrayerToTheSacredWinds",
    "LostPrayerToTheSacredWinds",
    "LostPrayerToTheSacredWinds",
    "SkywardAtlas",
    # "PrimordialJadeWingedSpear",
    "AThousandBlazingSuns",
    "WolfsGravestone",
    "SkywardPride",
    "KeyOfKhajNisut",
    "AquilaFavonia",
    # "AstralVulturesCrimsonPlumage",
    "LostPrayerToTheSacredWinds",
    "LostPrayerToTheSacredWinds",
    # "VortexVanquisher",
    "PeakPatrolSong",
    "RainbowSerpentsRainBow",
    "SequenceOfSolitude",
    "ChainBreaker",
    "ChainBreaker",
    "Cloudforged",
    "SongOfStillness",
    "IbisPiercer",
    "MouunsMoon",
    "FadingTwilight",
    "AlleyHunter",
    "TheViridescentHunt",
    "PrototypeCrescent",
    "Rust",
    "SacrificialBow",
    "TheStringless",
    "FavoniusWarbow",
    "FavoniusWarbow",
    "FavoniusWarbow",
    "EtherlightSpindlelute",
    "AshGravenDrinkingHorn",
    "BalladOfTheBoundlessBlue",
    "OathswornEye",
    "DodocoTales",
    # "PrototypeAmber",
    "SolarPearl",
    "SacrificialFragments",
    "TheWidsith",
    "TheWidsith",
    "FavoniusCodex",
    "TamayurateiNoOhanashi",
    "DialoguesOfTheDesertSages",
    "BalladOfTheFjords",
    "MissiveWindspear",
    "TheCatch",
    "KitainCrossSpear",
    "FavoniusLance",
    "FavoniusLance",
    "FavoniusLance",
    "FavoniusLance",
    "Deathmatch",
    "Deathmatch",
    "DragonsBane",
    "FlameForgedInsight",
    "EarthShaker",
    "UltimateOverlordsMegaMagicSword",
    "TidalShadow",
    "MailedFlower",
    "Akuoumaru",
    "SerpentSpine",
    "SerpentSpine",
    "Whiteblind",
    "PrototypeArchaic",
    "Rainslasher",
    "FavoniusGreatsword",
    "CalamityOfEshu",
    "FleuveCendreFerryman",
    "FinaleOfTheDeep",
    "WolfFang",
    "ToukabouShigure",
    "XiphosMoonlight",
    "SapwoodBlade",
    "KagotsurubeIsshin",
    "CinnabarSpindle",
    "AmenomaKageuchi",
    "TheBlackSword",
    "IronSting",
    "PrototypeRancour",
    "SacrificialSword",
    "SacrificialSword",
    "TheFlute",
    "FavoniusSword",
    "FavoniusSword",
    "FavoniusSword",
    "FavoniusSword",
    "SacrificialJade",
    "FootprintOfTheRainbow",
    "WavebreakersFin",
    "FavoniusLance",
    "LithicSpear",
    "FavoniusGreatsword",
    "SwordOfNarzissenkreuz",
    "WolfFang",
    "ScionOfTheBlazingSun",
    "SacrificialFragments",
    "SacrificialGreatsword",
    "FavoniusGreatsword",
    "FavoniusSword",
    "TheViridescentHunt",
    "LuxuriousSeaLord",
    "SacrificialGreatsword",
    "FavoniusGreatsword",
    "LionsRoar",
    "TheFlute",
    "FavoniusSword",
    "Hamayumi",
    "WindblumeOde",
    "FavoniusWarbow",
    "BalladOfTheFjords",
    "Rainslasher",
    "FavoniusGreatsword",
    "FavoniusSword",
    "FavoniusWarbow",
    "MappaMare",
    "TheBell",
    "SacrificialSword",
    "PrototypeArchaic",
    "SacrificialBow",
    "SacrificialBow",
    "SnowTombedStarsilver",
    "Rainslasher",
    "FlowerWreathedFeathers",
    "FlowerWreathedFeathers",
    "FlowerWreathedFeathers",
    "RangeGauge",
    "KingsSquire",
    "MitternachtsWaltz",
    "CompoundBow",
    "Rust",
    "Rust",
    "Rust",
    "SacrificialBow",
    "SacrificialBow",
    "SacrificialBow",
    "SacrificialBow",
    "SacrificialBow",
    "SacrificialBow",
    "SacrificialBow",
    "SacrificialBow",
    "TheStringless",
    "TheStringless",
    "TheStringless",
    "TheStringless",
    "TheStringless",
    "TheStringless",
    "TheStringless",
    "BlackmarrowLantern",
    "RingOfYaxche",
    "WaveridingWhirl",
    "WaveridingWhirl",
    "FlowingPurity",
    "FruitOfFulfillment",
    "HakushinRing",
    "Frostbearer",
    "WineAndSong",
    "EyeOfPerception",
    "EyeOfPerception",
    "EyeOfPerception",
    "EyeOfPerception",
    "EyeOfPerception",
    "EyeOfPerception",
    "SolarPearl",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "SacrificialFragments",
    "TheWidsith",
    "TheWidsith",
    "FavoniusCodex",
    "FavoniusCodex",
    "FavoniusCodex",
    "FavoniusCodex",
    "FavoniusCodex",
    "MountainBracingBolt",
    "MountainBracingBolt",
    "MountainBracingBolt",
    "MountainBracingBolt",
    "MountainBracingBolt",
    "MountainBracingBolt",
    "MountainBracingBolt",
    "MountainBracingBolt",
    "ProspectorsDrill",
    "RightfulReward",
    "Moonpiercer",
    "DragonspineSpear",
    "FavoniusLance",
    "LithicSpear",
    "LithicSpear",
    "CrescentPike",
    "PrototypeStarglitter",
    "DragonsBane",
    "DragonsBane",
    "DragonsBane",
    "DragonsBane",
    "DragonsBane",
    "DragonsBane",
    "DragonsBane",
    "DragonsBane",
    # "FruitfulHook",
    "TalkingStick",
    "TalkingStick",
    "ForestRegalia",
    "KatsuragikiriNagamasa",
    "LithicBlade",
    "Rainslasher",
    "Rainslasher",
    "Rainslasher",
    "SacrificialGreatsword",
    "SacrificialGreatsword",
    "SacrificialGreatsword",
    "TheBell",
    "TheBell",
    "TheBell",
    "TheBell",
    "TheBell",
    "TheBell",
    "SerenitysCall",
    "FluteOfEzpitzal",
    "SturdyBone",
    "SturdyBone",
    "SapwoodBlade",
    "TheBlackSword",
    "TheBlackSword",
    "LionsRoar",
    "LionsRoar",
    "LionsRoar",
    "LionsRoar",
    "LionsRoar",
    "LionsRoar",
    "LionsRoar",
    "SacrificialSword",
    "SacrificialSword",
    "SacrificialSword",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "TheFlute",
    "Slingshot",
    "Slingshot",
    "ThrillingTalesOfDragonSlayers",
    "ThrillingTalesOfDragonSlayers",
    "BlackTassel",
    "BlackTassel",
    "HarbingerOfDawn",
    "Slingshot",
    "MagicGuide",
    "DebateClub",
    "SkyriderSword",
    "HarbingerOfDawn",
    "SharpshootersOath",
    "ThrillingTalesOfDragonSlayers",
    "TwinNephrite",
    "DebateClub",
    "BloodtaintedGreatsword",
    "FilletBlade",
    "Messenger",
    "Messenger",
    "Messenger",
    "Messenger",
    "RecurveBow",
    "SharpshootersOath",
    "SharpshootersOath",
    "SharpshootersOath",
    "SharpshootersOath",
    "SharpshootersOath",
    "RavenBow",
    "RavenBow",
    "RavenBow",
    "RavenBow",
    "RavenBow",
    "RavenBow",
    "TwinNephrite",
    "TwinNephrite",
    "EmeraldOrb",
    "EmeraldOrb",
    "EmeraldOrb",
    "EmeraldOrb",
    "EmeraldOrb",
    "EmeraldOrb",
    "OtherworldlyStory",
    "OtherworldlyStory",
    "OtherworldlyStory",
    "MagicGuide",
    "MagicGuide",
    "MagicGuide",
    "BlackTassel",
    "BlackTassel",
    "Halberd",
    "Halberd",
    "Halberd",
    "WhiteTassel",
    "WhiteTassel",
    "WhiteTassel",
    "WhiteTassel",
    "WhiteTassel",
    "SkyriderGreatsword",
    "SkyriderGreatsword",
    "SkyriderGreatsword",
    "DebateClub",
    "DebateClub",
    "DebateClub",
    "WhiteIronGreatsword",
    "WhiteIronGreatsword",
    "WhiteIronGreatsword",
    "BloodtaintedGreatsword",
    "BloodtaintedGreatsword",
    "BloodtaintedGreatsword",
    "BloodtaintedGreatsword",
    "FerrousShadow",
    "FerrousShadow",
    "FerrousShadow",
    "FerrousShadow",
    "FerrousShadow",
    "FerrousShadow",
    "SkyriderSword",
    "SkyriderSword",
    "SkyriderSword",
    "FilletBlade",
    "FilletBlade",
    "DarkIronSword",
    "DarkIronSword",
    "TravelersHandySword",
    "TravelersHandySword",
    "HarbingerOfDawn",
    "HarbingerOfDawn",
    "CoolSteel",
    "CoolSteel",
    "CoolSteel",
]

preferences = create_preferences_from_dict(character_preferences, item_labels)
np.set_printoptions(threshold=sys.maxsize)
nested_lists = preferences.tolist()
print(nested_lists)
