def replace_strings_in_file(input_file, replacements):
    with open(input_file, 'r') as file:
        lines = file.readlines()

    with open(input_file, 'w') as file:
        for line in lines:
            for old_string, new_string in replacements.items():
                line = line.replace(old_string, new_string)
            file.write(line)


file_path = "2_artifactsMerged.txt"

string_map = {
    "Prayers for Wisdom (1)": "1",
    "Prayers for Destiny (1)": "2",
    "Prayers for Illumination (1)": "3",
    "Prayers to Springtime (1)": "4",
    "ATK +18% (2)": "5",
        "+18% ATK set (2)": "5",
        "+18 ATK% set (2)": "5",
        "18% ATK set (2)": "5",
        "+18% ATK set": "5",
        "+18% ATK Set (2)": "5",
        "A Day Carved From Rising Winds (2)": "5",
    "Elemental Mastery +80 (2)": "6",
        "+80 EM set (2)": "6",
        "80 EM set (2)": "6",
        "80 EM (2)": "6",
        "Night of the Sky's Unveiling (2)": "6",
        "Aubade of Morningstar and Moon (2)": "6",
    "Elemental Burst DMG +20% (2)": "7",
        "Noblesse Oblige (2)": "7",
    "Physical DMG Bonus +25% (2)": "8",
        "Pale Flame (2)": "8",
        "Bloodstained Chivalry (2)": "8",
        "+25% Physical DMG set (2)": "8",
    "Healing Bonus +15% (2)": "9",
        "+15% Healing Bonus set (2)": "9",
        "+15% Healing Bonus (2) set": "9",
        "+15% Healing Bonus (2)": "9",
    "Anemo DMG Bonus +15% (2)": "10",
        "+15% Anemo DMG set (2)": "10",
        "Viridescent Venerer (2)": "10",
        "+15% Anemo DMG Set (2)": "10",
    "Geo DMG Bonus +15% (2)": "11",
        "Archaic Petra (2)": "11",
    "Shield Strength +35% (2)": "12",
    "Electro RES +40% (2)": "13",
    "Electro DMG Bonus +15% (2)": "14",
        "Thundering Fury (2)": "14",
    "Pyro RES +40% (2)": "15",
    "Pyro DMG Bonus +15% (2)": "16",
        "Crimson Witch of Flames (2)": "16",
        "Crimson Witch (2)":  "16",
    "Cryo DMG Bonus +15% (2)": "17",
        "Blizzard Strayer (2)": "17",
        "+15% Cryo DMG set (2)": "17",
    "Hydro DMG Bonus +15% (2)": "18",
        "15% Hydro DMG Bonus set (2)": "18",
        "+15% Hydro DMG set (2)": "18",
        "+15% Hydro DMG set": "18",
    "HP +20% (2)": "19",
        "Tenacity of the Millelith (2)": "19",
        "Vourukasha's Glow (2)": "19",
        "+20% HP set (2)": "19",
        "+20% HP (2) set": "19",
        "20% HP set (2)": "19",
        "+20% HP (2)": "19",
        "+20% HP set": "19",
    "Energy Recharge +20% (2)": "20",
        "Emblem of Severed Fate (2)": "20",
        "+20% ER Set (2)": "20",
        "+20% ER set (2)": "20",
        "+20% Energy Recharge set (2)": "20",
        "Emblem Of Severed Fate (2)": "20",
        "Silken Moon's Serenade (2)": "20",
    "DEF +30% (2)": "21",
        "Husk of Opulent Dreams (2)": "21",
    "Dendro DMG Bonus +15% (2)": "22",
        "Deepwood Memories (2)": "22",
    "Normal/Charged Attack DMG +15% (2)": "23",
        "Marechaussee Hunter (2)": "23",
        "Marechausse Hunter (2)": "23",
    "Elemental Skill DMG +20% (2)": "24",
        "Golden Troupe (2)": "24",
    "Nightsoul Burst: Elemental Energy +6 (2)": "25",
    "Nightsoul's Blessing: DMG +15% (2)": "26",
    "Plunging Attack DMG +25% (2)": "27",
        "Long Night's Oath (2)": "27",
    "All Elemental RES +20% (2)": "28",
    "CRIT Rate +12% (2)": "29",
    "HP +1000 (2)": "30",
    "DEF +100 (2)": "31",
    "Incoming Healing Bonus +20% (2)": "32",
    "Gladiator's Finale (4)": "33",
    "Wanderer's Troupe (4)": "34",
    "Noblesse Oblige (4)": "35",
    "Bloodstained Chivalry (4)": "36",
    "Maiden Beloved (4)": "37",
    "Viridescent Venerer (4)": "38",
    "Archaic Petra (4)": "39",
        "Archaic Petra(4)": "39",
    "Retracing Bolide (4)": "40",
    "Thundersoother (4)": "41",
    "Thundering Fury (4)": "42",
    "Lavawalker (4)": "43",
    "Crimson Witch of Flames (4)": "44",
    "Blizzard Strayer (4)": "45",
    "Heart of Depth (4)": "46",
    "Tenacity of the Millelith (4)": "47",
    "Pale Flame (4)": "48",
    "Shimenawa's Reminiscence (4)": "49",
    "Emblem of Severed Fate (4)": "50",
    "Husk of Opulent Dreams (4)": "51",
    "Ocean-Hued Clam (4)": "52",
        "Ocean Hued Clam (4)": "52",
    "Vermillion Hereafter (4)": "53",
    "Echoes of an Offering (4)": "54",
    "Deepwood Memories (4)": "55",
    "Gilded Dreams (4)": "56",
    "Desert Pavilion Chronicle (4)": "57",
    "Flower of Paradise Lost (4)": "58",
    "Nymph's Dream (4)": "59",
    "Vourukasha's Glow (4)": "60",
    "Marechaussee Hunter (4)": "61",
    "Golden Troupe (4)": "62",
    "Song of Days Past (4)": "63",
    "Nighttime Whispers in the Echoing Woods (4)": "64",
    "Fragment of Harmonic Whimsy (4)": "65",
    "Unfinished Reverie (4)": "66",
    "Scroll of the Hero of Cinder City (4)": "67",
    "Obsidian Codex (4)": "68",
    "Long Night's Oath (4)": "69",
    "Finale of the Deep Galleries (4)": "70",
    "Night of the Sky's Unveiling (4)": "71",
    "Silken Moon's Serenade (4)": "72",
    "Aubade of Morningstar and Moon (4)": "73",
    "A Day Carved From Rising Winds (4)": "74",
        "A Day Carved from Rising Winds (4)": "74",
    "Resolution of Sojourner (4)": "75",
    "Tiny Miracle (4)": "76",
    "Berserker (4)": "77",
    "Instructor (4)": "78",
    "The Exile (4)": "79",
    "Defender's Will (4)": "80",
    "Brave Heart (4)": "81",
    "Martial Artist (4)": "82",
    "Gambler (4)": "83",
    "Scholar (4)": "84",
}
string_map_2 = {" Any (2)": "",
                " [Choose Two]": "",
                " [see notes]": "",
                " [Choose One]": "",
                " [Choose two]": "",
                " and ": ",",
                " / ": ",",
                "/": ",",
                " + ": ",",
                " ": ",",
                "*": "",
                "+": "",
                "Mixes of ": "",

                }

replace_strings_in_file(file_path, string_map)
replace_strings_in_file(file_path, string_map_2)
